import { Toaster } from "react-hot-toast";
import "./globals.css";
import localFont from 'next/font/local'

export const metadata = {
  title: "BLING",
  description: "Generated by create next app",
};

const satoshi = localFont({
  src: './fonts/Satoshi-Variable.woff2',
  display: 'swap'
})

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${satoshi.className}`}
      >
        {children}

        <Toaster />
      </body>
    </html>
  );
}
